server:
  port: 8081
  servlet:
    context-path: /finance

spring:
  application:
    name: finance
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      default_schema: bankingdb
      show-sql: true
  docker:
    compose:
      skip:
        in-tests: false
      enabled: true
      file: classpath:docker/docker-compose.yml

spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    filter: true
    operations-sorter: alpha
  api-docs.path: /v3/rest-api-docs

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG